export const COMPANY_DOMAIN = '@tecnicagroup.hu';
export const QR_HOST = 'scan.tecnicagroup.hu';

export const STAGES = ['injection','padprint','assembly','qc','packaging','warehouse'] as const;
export type Stage = typeof STAGES[number];

export const BOXES = [
  {code:'060', pairs:56},
  {code:'050', pairs:64},
  {code:'045', pairs:72},
  {code:'035', pairs:76},
  {code:'020', pairs:90},
  {code:'025', pairs:108},
] as const;

export interface Lancio {
  n: number; y: string; m: string; c: string; cc: string;
  col: string; pa: number; comm: string; cn: string;
}

export const LANCIOS: Lancio[] = [
  {n:100,y:'2025',m:'MACH1 LV 130 TD2',c:'101C04 G0',cc:'381',col:'ICON ORANGE',pa:750,comm:'TSKB 2025 10562 AA',cn:'10562'},
  {n:200,y:'2025',m:'MACH1 LV 105 W TD2',c:'201C06 G0',cc:'L6D',col:'IRIDESC.GREEN/GOLD',pa:1000,comm:'TSKB 2025 10952 AA',cn:'10952'},
  {n:300,y:'2025',m:'MACH BOA MV 110',c:'101G56 G0',cc:'741',col:'BLACK/RED',pa:1469,comm:'TSKB 2025 11182 AA',cn:'11182'},
  {n:400,y:'2025',m:'SPEEDMACHINE 3 85 W BOA (GW)',c:'050Q22 00',cc:'4A2',col:'NERO/BIANCO/ROSA',pa:1489,comm:'TSKB 2025 11898 AA',cn:'11898'},
  {n:500,y:'2025',m:'MACH1 LV 120 TD2',c:'101C06 G0',cc:'40D',col:'DARK PROGR.GREEN',pa:1039,comm:'TSKB 2025 12322 AA',cn:'12322'},
  {n:600,y:'2025',m:'HF 85 W (GW)',c:'050K13 01',cc:'4F5',col:'NERO/VERDE/ACQUA',pa:1500,comm:'TSKB 2025 12863 AA',cn:'12863'},
  {n:800,y:'2026',m:'PRO MACHINE 3 130 S (GW)',c:'050D00 00',cc:'4Y5',col:'CAMO NERO',pa:594,comm:'TSKB 2026 00013 AA',cn:'00013'},
  {n:900,y:'2026',m:'PRO MACHINE 3 120 (GW)',c:'050D06 00',cc:'688',col:'GRIGIO/NERO/ROSSO',pa:1000,comm:'TSKB 2026 00472 AA',cn:'00472'},
  {n:1000,y:'2026',m:'PRO MACHINE 3 130 (GW)',c:'050D02 00',cc:'N96',col:'NERO/GRIGIO/ROSSO',pa:1007,comm:'TSKB 2026 01042 AA',cn:'01042'},
  {n:1100,y:'2026',m:'HF 120 (GW)',c:'050K06 01',cc:'M99',col:'ANTRACITE/NERO/ROSSO',pa:1000,comm:'TSKB 2026 01568 AA',cn:'01568'},
  {n:1100,y:'2026',m:'PRO MACHINE 3 130 S (GW)',c:'050D00 00',cc:'4Y5',col:'CAMO NERO',pa:620,comm:'TSKB 2026 01541 AA',cn:'01541'},
  {n:1100,y:'2026',m:'MACH BOA HV 110 X',c:'101973 G5',cc:'606',col:'BLACK/ORANGE',pa:800,comm:'TSKB 2026 02013 AA',cn:'02013'},
  {n:1200,y:'2026',m:'DOBERMANN 5 RD-93(EXTRA STIFF)',c:'050A06 01',cc:'100',col:'NERO',pa:225,comm:'TSKB 2026 02108 AA',cn:'02108'},
  {n:1300,y:'2026',m:'DOBERMANN 5 96 (MEDIUM)',c:'050A22 01',cc:'100',col:'NERO',pa:700,comm:'TSKB 2026 02733 AA',cn:'02733'},
  {n:1400,y:'2026',m:'SPEEDMACHINE 3 130 (GW)',c:'050G14 00',cc:'7T1',col:'NERO/ANTRACITE/ROSSO',pa:1000,comm:'TSKB 2026 03473 AA',cn:'03473'},
  {n:1400,y:'2026',m:'THE CRUISE 120 (GW)',c:'050640 03',cc:'N96',col:'NERO/GRIGIO/ROSSO',pa:656,comm:'TSKB 2026 03565 AA',cn:'03565'},
  {n:1400,y:'2026',m:'SPEEDMACHINE 3 130 (GW) SHELL',c:'050X20 00',cc:'7T1',col:'NERO/ANTRACITE/ROSSO',pa:14,comm:'TSKB 2026 04147 AA',cn:'04147'},
  {n:1400,y:'2026',m:'PRO MACHINE 3 130 S (GW)',c:'050D00 00',cc:'4Y5',col:'CAMO NERO',pa:600,comm:'TSKB 2026 03457 AA',cn:'03457'},
];

export const LANCIO_PDFS: Record<string, string> = {
  '10562':'uploads/Lancio 100.PDF','10952':'uploads/Lancio 200.PDF',
  '11182':'uploads/Lancio 300.PDF','11898':'uploads/Lancio 400.PDF',
  '12322':'uploads/Lancio 500.PDF','12863':'uploads/Lancio_600_700.PDF',
  '00013':'uploads/Lancio 800.PDF','00472':'uploads/Lancio 900.PDF',
  '01042':'uploads/Lancio 1000.PDF','01568':'uploads/lancio1100_2026_1.PDF',
  '01541':'uploads/lancio1100_2026_2.PDF','02013':'uploads/lancio1100_2026_3.PDF',
  '02108':'uploads/lancio1200_2026.PDF','02733':'uploads/Lancio 1300.PDF',
  '03473':'uploads/3473.PDF','03565':'uploads/3565.PDF',
  '04147':'uploads/4147.PDF','03457':'uploads/Lancio 1400.PDF',
};

export const LSIZES: Record<string, {mp:string;qty:number}[]> = {
  '10562':[{mp:'24.5',qty:30},{mp:'25.5',qty:222},{mp:'26.0',qty:25},{mp:'26.5',qty:473}],
  '10952':[{mp:'22.5',qty:48},{mp:'23.5',qty:175},{mp:'24.0',qty:20},{mp:'24.5',qty:291},{mp:'25.0',qty:22},{mp:'25.5',qty:279},{mp:'26.0',qty:13},{mp:'26.5',qty:127},{mp:'27.5',qty:25}],
  '11182':[{mp:'25.5',qty:132},{mp:'26.0',qty:26},{mp:'26.5',qty:310},{mp:'27.0',qty:45},{mp:'27.5',qty:387},{mp:'28.0',qty:49},{mp:'28.5',qty:311},{mp:'29.0',qty:28},{mp:'29.5',qty:145},{mp:'30.5',qty:36}],
  '11898':[{mp:'22.5',qty:96},{mp:'23.5',qty:336},{mp:'24.5',qty:509},{mp:'25.5',qty:422},{mp:'26.5',qty:126}],
  '12322':[{mp:'24.5',qty:31},{mp:'25.5',qty:192},{mp:'26.5',qty:384},{mp:'27.5',qty:432}],
  '12863':[{mp:'23.0',qty:15},{mp:'23.5',qty:206},{mp:'24.0',qty:32},{mp:'24.5',qty:429},{mp:'25.0',qty:50},{mp:'25.5',qty:459},{mp:'26.0',qty:30},{mp:'26.5',qty:249},{mp:'27.5',qty:30}],
  '00013':[{mp:'24.5',qty:39},{mp:'25.5',qty:77},{mp:'26.5',qty:125},{mp:'27.5',qty:173},{mp:'28.5',qty:108},{mp:'29.5',qty:72}],
  '00472':[{mp:'24.5',qty:29},{mp:'25.5',qty:125},{mp:'26.5',qty:240},{mp:'27.5',qty:288},{mp:'28.5',qty:252},{mp:'29.5',qty:66}],
  '01042':[{mp:'24.5',qty:29},{mp:'25.5',qty:77},{mp:'26.5',qty:221},{mp:'27.5',qty:240},{mp:'28.5',qty:274},{mp:'29.5',qty:130},{mp:'30.5',qty:36}],
  '01568':[{mp:'24.0',qty:3},{mp:'24.5',qty:26},{mp:'25.0',qty:5},{mp:'25.5',qty:72},{mp:'26.0',qty:10},{mp:'26.5',qty:163},{mp:'27.0',qty:20},{mp:'27.5',qty:259},{mp:'28.0',qty:20},{mp:'28.5',qty:220},{mp:'29.0',qty:12},{mp:'29.5',qty:132},{mp:'30.0',qty:8},{mp:'30.5',qty:42},{mp:'31.0',qty:8}],
  '01541':[{mp:'23.5',qty:20},{mp:'24.5',qty:29},{mp:'25.5',qty:80},{mp:'26.5',qty:125},{mp:'27.5',qty:186},{mp:'28.5',qty:36},{mp:'29.5',qty:108},{mp:'30.5',qty:36}],
  '02013':[{mp:'26.5',qty:91},{mp:'27.0',qty:10},{mp:'27.5',qty:211},{mp:'28.0',qty:6},{mp:'28.5',qty:232},{mp:'29.0',qty:5},{mp:'29.5',qty:161},{mp:'30.5',qty:58},{mp:'31.5',qty:17},{mp:'32.5',qty:9}],
  '02108':[{mp:'24.5',qty:17},{mp:'25.5',qty:37},{mp:'26.5',qty:44},{mp:'27.5',qty:63},{mp:'28.5',qty:42},{mp:'29.5',qty:22}],
  '02733':[{mp:'22.5',qty:30},{mp:'23.5',qty:64},{mp:'24.5',qty:126},{mp:'25.5',qty:161},{mp:'26.5',qty:159},{mp:'27.5',qty:110},{mp:'28.5',qty:50}],
  '03473':[{mp:'24.5',qty:25},{mp:'25.5',qty:20},{mp:'26.5',qty:172},{mp:'27.5',qty:340},{mp:'28.5',qty:230},{mp:'29.5',qty:145},{mp:'30.0',qty:3},{mp:'30.5',qty:60},{mp:'31.0',qty:5}],
  '03565':[{mp:'26.5',qty:172},{mp:'27.5',qty:159},{mp:'28.5',qty:127},{mp:'29.5',qty:127},{mp:'30.5',qty:26},{mp:'31.0',qty:4},{mp:'31.5',qty:28},{mp:'32.0',qty:4},{mp:'32.5',qty:9}],
  '04147':[{mp:'25.5',qty:1},{mp:'26.5',qty:2},{mp:'27.5',qty:3},{mp:'28.5',qty:4},{mp:'29.5',qty:3},{mp:'30.5',qty:1}],
  '03457':[{mp:'22.5',qty:20},{mp:'25.5',qty:45},{mp:'26.5',qty:170},{mp:'27.5',qty:135},{mp:'28.5',qty:175},{mp:'29.5',qty:30},{mp:'30.5',qty:25}],
};

export type Lang = 'en' | 'hu' | 'it';

export const T: Record<Lang, Record<string,string>> = {
  en: {
    tagline:'Asset & inventory scanner', scan:'Scan QR code', scanHint:'Point your camera at any Tecnica asset tag',
    recent:'Recent scans', noRecent:'No scans yet — tap Scan to read your first tag.',
    signedInAs:'Signed in', signIn:'Sign in', signOut:'Sign out',
    guest:'Guest access', guestSub:'Public asset tags only',
    publicTag:'Public', restrictedTag:'Restricted',
    location:'Location', details:'Details', maintenance:'Maintenance & work orders',
    history:'History', documents:'Documents',
    restrictedTitle:'Restricted asset',
    restrictedMsg:'This tag is limited to registered staff. Sign in with your company account to view its details.',
    actions:'Actions', move:'Move / relocate', checkout:'Check out', report:'Report an issue',
    back:'Back', cancel:'Cancel',
    emailL:'Company email', passwordL:'Password',
    loginTitle:'Company sign in', loginSub:'Use your @tecnicagroup.hu account',
    loginNote:'Public tags are readable by anyone. Restricted tags require a registered company account.',
    wrongDomain:'Enter a valid @tecnicagroup.hu email and password.',
    scanningT:'Scanning…', tapDemo:'Demo — tap a tag to simulate a scan',
    moved:'Move started', checkedOut:'Checked out', reported:'Issue reported',
    s_inStock:'In stock', s_attention:'Needs attention', s_operational:'Operational',
    s_maintenanceDue:'Maintenance due', s_inProduction:'In production',
    createTag:'Create QR tag', adminTitle:'Create QR tag',
    adminSub:'Generate a printable asset label',
    fName:'Asset name', fId:'Asset ID', fType:'Type', fAccess:'Access', fZone:'Location',
    tPallet:'Pallet', tMachine:'Machine', tLocation:'Location',
    labelPreview:'Label preview', encLink:'Encoded link',
    downloadLabel:'Download label', addToScanner:'Save & add to scanner',
    tagCreated:'Tag created & added to scanner',
    idHint:'Used in the QR link',
    helpPublic:'Anyone can read this tag without signing in.',
    helpRestricted:'Only registered staff can open this tag.',
    material:'Material', process:'Process parameters', prodStage:'Production stage',
    stageStep:'Stage', stDone:'Completed', stCurrent:'In progress', stPending:'Pending',
    stage_injection:'Injection moulding', stage_padprint:'Pad printing',
    stage_assembly:'Assembly', stage_qc:'Quality control',
    stage_packaging:'Packaging', stage_warehouse:'Warehouse',
    doc_drawing:'Drawing', doc_spec:'Specification', doc_quality:'Quality',
    doc_safety:'Safety', doc_instruction:'Instruction',
    fStage:'Production stage',
    batchTitle:'Batch label printing', batchSub:'Print cage QR labels from a job order',
    batchEntry:'Cage label printing', batchEntrySub:'Generate QR labels by commessa or job order',
    jobOrderL:'Job order number', loadJob:'Load', jobNotFound:'Job order not found.',
    demoJobs:'Demo job orders', jobPlaceholder:'e.g. JO-4471',
    cagesToPrint:'Cages to print', cage:'Cage', sizeL:'Size', qtyPcs:'pcs',
    printSheet:'Print label sheet', batchTotals:'{cages} cages · {pairs} pairs',
    partTypeL:'Part type', scafoL:'Scafo', gambettoL:'Gambetto', cageCapL:'Pairs per cage',
    tapLabelHint:'Tap a label to preview it',
    regEntry:'Register material to location', regEntrySub:'Scan a cage, then a location',
    regTitle:'Register material', regSub:'Scan the material, then its location',
    scanMaterial:'Scan material / cage', scanLocation:'Scan location',
    stepMaterial:'Material', stepLocation:'Location',
    rescan:'Re-scan', confirmReg:'Confirm registration',
    regDoneTitle:'Registration complete', regDoneMsg:'{m} is now stored at {l}.',
    viewItem:'View item', regAnother:'Register another',
    lSubtitle:'Sign in with your company account, or continue as a guest to read public tags.',
    lGuest:'Continue as guest', lOr:'or',
    lanciEntry:'Lanci · Listafa & Bolla', lanciEntrySub:'Find a production order, print listafa & bolla',
    lanciTitle:'Production orders', lanciSearch:'Search lancio, commessa or model',
    commessaL:'Commessa', articoloL:'Articolo', coloreL:'Colour',
    paiaTot:'Total pairs', sizesL:'Sizes', printListafa:'Print listafa', printBolla:'Crea Bolla',
    listafaTitle:'Documenti lavorazione reparto',
    bollaTitle:'Bolla · pallet labels', perBox:'Pairs per box',
    orderPairs:'Order (pairs)', remainder:'Remainder', boxesNeeded:'Boxes needed',
    boxType:'Box type', boxWordL:'Box',
    modello:'MODELLO', codice:'CODICE', taglia:'TAGLIA', paiaWord:'PAIA', commessaWord:'COMMESSA',
    scanFindsLancio:'Scanned cage — linked lancio found',
    viewMap:'View factory map', orderFill:'Quick-fill from production order',
    orderFillSub:'Tap a commessa to auto-fill the form',
    welcomeBack:'Welcome back',
  },
  hu: {
    tagline:'Eszköz- és készletszkenner', scan:'QR-kód beolvasása', scanHint:'Irányítsa a kamerát egy Tecnica eszközcímkére',
    recent:'Legutóbbi beolvasások', noRecent:'Még nincs beolvasás — érintse a Beolvasás gombot.',
    signedInAs:'Bejelentkezve', signIn:'Bejelentkezés', signOut:'Kijelentkezés',
    guest:'Vendég hozzáférés', guestSub:'Csak nyilvános címkék',
    publicTag:'Nyilvános', restrictedTag:'Korlátozott',
    location:'Helyszín', details:'Részletek', maintenance:'Karbantartás és munkalapok',
    history:'Előzmények', documents:'Dokumentumok',
    restrictedTitle:'Korlátozott eszköz',
    restrictedMsg:'Ez a címke csak regisztrált munkatársaknak elérhető. Jelentkezzen be céges fiókjával.',
    actions:'Műveletek', move:'Áthelyezés', checkout:'Kivételezés', report:'Hiba jelentése',
    back:'Vissza', cancel:'Mégse',
    emailL:'Céges e-mail', passwordL:'Jelszó',
    loginTitle:'Céges bejelentkezés', loginSub:'Használja a @tecnicagroup.hu fiókját',
    loginNote:'A nyilvános címkék bárki számára olvashatók. A korlátozott címkékhez regisztrált céges fiók szükséges.',
    wrongDomain:'Adjon meg érvényes @tecnicagroup.hu e-mailt és jelszót.',
    scanningT:'Beolvasás…', tapDemo:'Demó — koppintson egy címkére',
    moved:'Áthelyezés elindítva', checkedOut:'Kivételezve', reported:'Hiba jelentve',
    s_inStock:'Készleten', s_attention:'Figyelmet igényel', s_operational:'Üzemképes',
    s_maintenanceDue:'Karbantartás esedékes', s_inProduction:'Gyártásban',
    createTag:'QR-címke létrehozása', adminTitle:'QR-címke létrehozása',
    adminSub:'Nyomtatható eszközcímke készítése',
    fName:'Eszköz neve', fId:'Eszköz azonosító', fType:'Típus', fAccess:'Hozzáférés', fZone:'Helyszín',
    tPallet:'Raklap', tMachine:'Gép', tLocation:'Helyszín',
    labelPreview:'Címke előnézet', encLink:'Kódolt link',
    downloadLabel:'Címke letöltése', addToScanner:'Mentés és hozzáadás',
    tagCreated:'Címke létrehozva és hozzáadva',
    idHint:'A QR-linkben használt',
    helpPublic:'Bárki beolvashatja bejelentkezés nélkül.',
    helpRestricted:'Csak regisztrált munkatársak nyithatják meg.',
    material:'Anyag', process:'Folyamatparaméterek', prodStage:'Gyártási szakasz',
    stageStep:'Szakasz', stDone:'Kész', stCurrent:'Folyamatban', stPending:'Függőben',
    stage_injection:'Fröccsöntés', stage_padprint:'Tamponnyomás',
    stage_assembly:'Összeszerelés', stage_qc:'Minőségellenőrzés',
    stage_packaging:'Csomagolás', stage_warehouse:'Raktár',
    doc_drawing:'Rajz', doc_spec:'Specifikáció', doc_quality:'Minőség',
    doc_safety:'Biztonság', doc_instruction:'Utasítás',
    fStage:'Gyártási szakasz',
    batchTitle:'Ketrec-címke nyomtatás', batchSub:'Ketrec QR-címkék nyomtatása munkaszámból',
    batchEntry:'Ketrec-címkék nyomtatása', batchEntrySub:'QR-címkék generálása commessa vagy munkaszám alapján',
    jobOrderL:'Munkaszám', loadJob:'Betöltés', jobNotFound:'Munkaszám nem található.',
    demoJobs:'Demó munkaszámok', jobPlaceholder:'pl. JO-4471',
    cagesToPrint:'Nyomtatandó ketrecek', cage:'Ketrec', sizeL:'Méret', qtyPcs:'db',
    printSheet:'Címkelap nyomtatása', batchTotals:'{cages} ketrec · {pairs} pár',
    partTypeL:'Alkatrész típusa', scafoL:'Scafo', gambettoL:'Gambetto', cageCapL:'Pár / ketrec',
    tapLabelHint:'Koppintson egy címkére az előnézethez',
    regEntry:'Anyag regisztrálása helyre', regEntrySub:'Olvasson be egy ketrecet, majd egy helyet',
    regTitle:'Anyag regisztrálása', regSub:'Olvassa be az anyagot, majd a helyét',
    scanMaterial:'Anyag / ketrec beolvasása', scanLocation:'Helyszín beolvasása',
    stepMaterial:'Anyag', stepLocation:'Helyszín',
    rescan:'Újra', confirmReg:'Regisztráció megerősítése',
    regDoneTitle:'Regisztráció kész', regDoneMsg:'{m} mostantól itt van: {l}.',
    viewItem:'Tétel megtekintése', regAnother:'Új regisztráció',
    lSubtitle:'Jelentkezzen be céges fiókjával, vagy folytassa vendégként.',
    lGuest:'Folytatás vendégként', lOr:'vagy',
    lanciEntry:'Lanciók · Listafa & Bolla', lanciEntrySub:'Munkaszám keresése, listafa és bolla nyomtatás',
    lanciTitle:'Gyártási rendelések', lanciSearch:'Keresés: lanció, commessa vagy modell',
    commessaL:'Commessa', articoloL:'Cikkszám', coloreL:'Szín',
    paiaTot:'Összes pár', sizesL:'Méretek', printListafa:'Listafa nyomtatása', printBolla:'Bolla nyomtatása',
    listafaTitle:'Documenti lavorazione reparto',
    bollaTitle:'Bolla · raklapcímkék', perBox:'Pár / doboz',
    orderPairs:'Megrendelés (pár)', remainder:'Maradék', boxesNeeded:'Szükséges doboz',
    boxType:'Doboz típus', boxWordL:'Doboz',
    modello:'MODELLO', codice:'CODICE', taglia:'TAGLIA', paiaWord:'PAIA', commessaWord:'COMMESSA',
    scanFindsLancio:'Beolvasott ketrec — lanció megtalálva',
    viewMap:'Gyárrajz megtekintése', orderFill:'Kitöltés gyártási rendelésből',
    orderFillSub:'Érintsen egy commessát a QR-címke generálásához',
    welcomeBack:'Üdvözöljük',
  },
  it: {
    tagline:'Scanner di asset e magazzino', scan:'Scansiona QR', scanHint:'Inquadra un tag asset Tecnica con la fotocamera',
    recent:'Scansioni recenti', noRecent:'Nessuna scansione — tocca Scansiona per iniziare.',
    signedInAs:'Connesso', signIn:'Accedi', signOut:'Esci',
    guest:'Accesso ospite', guestSub:'Solo tag pubblici',
    publicTag:'Pubblico', restrictedTag:'Riservato',
    location:'Posizione', details:'Dettagli', maintenance:'Manutenzione e ordini di lavoro',
    history:'Cronologia', documents:'Documenti',
    restrictedTitle:'Asset riservato',
    restrictedMsg:'Questo tag è riservato al personale registrato. Accedi con l\'account aziendale.',
    actions:'Azioni', move:'Sposta / riposiziona', checkout:'Preleva', report:'Segnala un problema',
    back:'Indietro', cancel:'Annulla',
    emailL:'Email aziendale', passwordL:'Password',
    loginTitle:'Accesso aziendale', loginSub:'Usa il tuo account @tecnicagroup.hu',
    loginNote:'I tag pubblici sono leggibili da chiunque. I tag riservati richiedono un account aziendale.',
    wrongDomain:'Inserisci un\'email @tecnicagroup.hu e una password valide.',
    scanningT:'Scansione…', tapDemo:'Demo — tocca un tag per simulare la scansione',
    moved:'Spostamento avviato', checkedOut:'Prelevato', reported:'Problema segnalato',
    s_inStock:'Disponibile', s_attention:'Richiede attenzione', s_operational:'Operativo',
    s_maintenanceDue:'Manutenzione richiesta', s_inProduction:'In produzione',
    createTag:'Crea tag QR', adminTitle:'Crea tag QR',
    adminSub:'Genera un\'etichetta stampabile',
    fName:'Nome asset', fId:'ID asset', fType:'Tipo', fAccess:'Accesso', fZone:'Posizione',
    tPallet:'Pallet', tMachine:'Macchina', tLocation:'Posizione',
    labelPreview:'Anteprima etichetta', encLink:'Link codificato',
    downloadLabel:'Scarica etichetta', addToScanner:'Salva e aggiungi',
    tagCreated:'Tag creato e aggiunto',
    idHint:'Usato nel link QR',
    helpPublic:'Chiunque può leggerlo senza accedere.',
    helpRestricted:'Solo il personale registrato può aprirlo.',
    material:'Materiale', process:'Parametri di processo', prodStage:'Fase di produzione',
    stageStep:'Fase', stDone:'Completata', stCurrent:'In corso', stPending:'In attesa',
    stage_injection:'Stampaggio a iniezione', stage_padprint:'Tampografia',
    stage_assembly:'Assemblaggio', stage_qc:'Controllo qualità',
    stage_packaging:'Imballaggio', stage_warehouse:'Magazzino',
    doc_drawing:'Disegno', doc_spec:'Specifica', doc_quality:'Qualità',
    doc_safety:'Sicurezza', doc_instruction:'Istruzione',
    fStage:'Fase di produzione',
    batchTitle:'Stampa etichette lotto', batchSub:'Stampa etichette QR gabbia da un ordine',
    batchEntry:'Stampa etichette gabbia', batchEntrySub:'Genera etichette QR per commessa o ordine',
    jobOrderL:'Numero ordine', loadJob:'Carica', jobNotFound:'Ordine non trovato.',
    demoJobs:'Ordini demo', jobPlaceholder:'es. JO-4471',
    cagesToPrint:'Gabbie da stampare', cage:'Gabbia', sizeL:'Taglia', qtyPcs:'pz',
    printSheet:'Stampa foglio etichette', batchTotals:'{cages} gabbie · {pairs} paia',
    partTypeL:'Tipo componente', scafoL:'Scafo', gambettoL:'Gambetto', cageCapL:'Paia per gabbia',
    tapLabelHint:'Tocca un\'etichetta per vederla',
    regEntry:'Registra materiale in posizione', regEntrySub:'Scansiona una gabbia, poi una posizione',
    regTitle:'Registra materiale', regSub:'Scansiona il materiale, poi la posizione',
    scanMaterial:'Scansiona materiale / gabbia', scanLocation:'Scansiona posizione',
    stepMaterial:'Materiale', stepLocation:'Posizione',
    rescan:'Ripeti', confirmReg:'Conferma registrazione',
    regDoneTitle:'Registrazione completata', regDoneMsg:'{m} ora si trova in {l}.',
    viewItem:'Vedi elemento', regAnother:'Nuova registrazione',
    lSubtitle:'Accedi con l\'account aziendale o continua come ospite per i tag pubblici.',
    lGuest:'Continua come ospite', lOr:'oppure',
    lanciEntry:'Lanci · Listafa & Bolla', lanciEntrySub:'Trova un lancio, stampa listafa e bolla',
    lanciTitle:'Ordini di produzione', lanciSearch:'Cerca lancio, commessa o modello',
    commessaL:'Commessa', articoloL:'Articolo', coloreL:'Colore',
    paiaTot:'Paia totali', sizesL:'Taglie', printListafa:'Stampa listafa', printBolla:'Stampa bolla',
    listafaTitle:'Documenti lavorazione reparto',
    bollaTitle:'Bolla · etichette pallet', perBox:'Paia per scatola',
    orderPairs:'Ordine (paia)', remainder:'Resto', boxesNeeded:'Scatole necessarie',
    boxType:'Tipo scatola', boxWordL:'Scatola',
    modello:'MODELLO', codice:'CODICE', taglia:'TAGLIA', paiaWord:'PAIA', commessaWord:'COMMESSA',
    scanFindsLancio:'Gabbia scansionata — lancio trovato',
    viewMap:'Visualizza mappa stabilimento', orderFill:'Compila da ordine di produzione',
    orderFillSub:'Tocca una commessa per generare la sua etichetta QR',
    welcomeBack:'Benvenuto',
  },
};
